name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    name: Build DiceDB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Start DiceDB server
        run: |
          ./dicedb --engine ironhawk --log-level debug --enable-wal > dicedb.log 2>&1 &
          echo $! > dicedb.pid
          # Wait for server to be ready
          for i in {1..30}; do
            if nc -z localhost 7379; then
              echo "DiceDB server is ready"
              break
            fi
            echo "Waiting for DiceDB server... ($i/30)"
            sleep 1
          done

      - name: Run tests
        run: make test

      - name: Stop DiceDB server
        if: always()
        run: |
          if [ -f dicedb.pid ]; then
            kill $(cat dicedb.pid) || true
            rm dicedb.pid
          fi

      - name: Upload DiceDB logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dicedb-logs
          path: dicedb.log
          retention-days: 7

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: dicedb-binary
          path: ./dicedb
          retention-days: 7
